### ISSUE TITLE
mpf_t?

### ISSUE THREAD

**Issue by cdycdr** [wezeku/Mpir.NET#4]
will mpf_t be available?

btw: wich generator do you use for generating the native mappings?

**Comment by wezeku** [comment]
I use mpir mainly for cryptography, so I don't have any plans for mpf_t. I would however accept a pull request that adds support for it.

The generator is in https://github.com/wezeku/Mpir.NET/tree/master/xmpir_ModdedForMpir.NET/generator and is written by Sergey Bochkanov (http://www.alglib.net/).

**Comment by cdycdr** [comment]
ah, thanks. i see.
will have a look.
