### ISSUE TITLE
Please provide constructor overload for working with Byte array segments

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [wezeku/Mpir.NET#5]
It would really help if you could provide this Constructor overload

 Public Sub New(bytes() As Byte, order As Integer,offset as Integer, length as Integer)

IT would be useful for working with byte array segments.

**Comment by wezeku** [comment]
It's already there: http://wezeku.github.io/Mpir.NET/doxygenOutput/html/class_mpir_1_1_n_e_t_1_1mpz__t.html#a60ca40b9f8ab6e123dbbe880fe499154

To get offset+length feature, use array slicing.

**Comment by CharlesOkwuagwu** [comment]
Ah, i will check again, i might have missed it
