### ISSUE TITLE
Negative power by module

### ISSUE THREAD

**Issue by YuriyTigiev** [wezeku/Mpir.NET#9]
Hello, 

The following source code returns the incorrect result. Instead of value 5 it show 6.
Platform target: x64

        static void Main(string[] args)
        {
            mpz_t a = new mpz_t(3);
            mpz_t b = new mpz_t(7);
            mpz_t c;

            c = a.PowerMod(-1, b);
            System.Console.WriteLine("{0}", c);

        }

**Comment by wezeku** [comment]
Fixed it. Thanks for reporting the bug!
